### ISSUE TITLE
The requirement of being fullscreen could be fulfilled by other means than the Fullscreen API

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/screen-orientation#10]

**Comment by mounirlamouri** [comment]
Unless browsers bind their fullscreen mode to the fullscreen API?

**Comment by mounirlamouri** [comment]
There is no more requirement. I believe this is fixed. @marcoscaceres please reopen if I misunderstood.

**Comment by marcoscaceres** [comment]
Yep. All is good.
