### ISSUE TITLE
Steps for updating orientation information are misleading

### ISSUE THREAD

**Issue by alexshalamov** [w3c/screen-orientation#100]
In chapter 4.1, steps for updating orientation information refer to a document in several places. Other parts of spec refer to document object as well.

It is misleading, since the ScreenOrientation is part of Screen interface, not the document. Screen orientation may affect document orientation (rendering), not vice-versa. Also, screen orientation can be locked from API (or on platform level), document interface does not have API to lock / unlock it’s orientation.

Following statements imply that document has orientation information:

> The steps to update the orientation information of a document are as follows:

> Set the document's current orientation angle…

> The decision whether the document's current orientation type should be set to *-primary or *-secondary is up to the user agent.

**Comment by xfq** [comment]
What about replacing "document" with "device"?

**Comment by xfq** [comment]
@mounirlamouri WDYT?

**Comment by mounirlamouri** [comment]
In these places, the document is taken from the browsing context. IIRC, the spec meant to associate some data with a document. I do not think that switching to device is the right change. Maybe we can make it clearer that the "current orientation angle" is an information associated to a document.

**Comment by Johanna-hub** [comment]
I can try to clarify this point in the spec if that is helpful

**Comment by marcoscaceres** [comment]
The spec now directly works on either internal slots associated with a particular "responsible document" object, so I think this has been addressed. In Gecko, we match the spec precisely as specified.
