### ISSUE TITLE
Orientation angle to orientation type mapping for 2-in-1 devices

### ISSUE THREAD

**Issue by alexshalamov** [w3c/screen-orientation#101]
Devices that could change mode of operation (e.g., 2-in-1s) might have different preferences for *-primary *-secondary types for different modes (tablet | laptop), therefore, in some cases, angle cannot be precisely mapped to orientation type. Thus, it would be difficult to fulfill following requirement:

> However, a user agent must keep the current orientation type and the current orientation angle relation consistent for any given document.

**Comment by marcoscaceres** [comment]
As angle is kinda useless/inconsistent anyway, I'd be fine with removing this requirement entirely.

**Comment by marcoscaceres** [comment]
No longer in the draft.
