### ISSUE TITLE
Wide review tracker

### ISSUE THREAD

**Issue by LJWatson** [w3c/screen-orientation#102]
A11y: [complete](https://www.w3.org/WAI/APA/wiki/The_Screen_Orientation_API)
[Comments from APA WG](https://lists.w3.org/Archives/Public/public-webapps/2018AprJun/0035.html)

Device APIs: [complete](https://www.w3.org/2009/dap/track/actions/787)
Issues #101, #100, and #99

I18n: [complete](https://github.com/w3c/i18n-activity/issues/265) - no issues

Privacy: complete (no tracker) - no issues

Security: complete: no tracker
Issue #96 

TAG: [complete](https://github.com/w3ctag/design-reviews/issues/157#issuecomment-317734363)
Issue #105

**Comment by LJWatson** [comment]
marcoscaceres and  @mounirlamouri, do you think any of the issues open against the spec need resolution before we move to CR?

**Comment by marcoscaceres** [comment]
we might need to find new editors for this spec. Mounir and I don't seem to have time to attend to it properly.

**Comment by LJWatson** [comment]
We can do that, but it would be a shame to lose you both this close to the finishing line.

Would you have time to triage the five issues noted above, to get a sense of which (if any) need to be addressed before CR and what that might entail?

**Comment by LJWatson** [comment]
It's sad, but if neither of you is able to continue editing, I'll put out a call for new editors. Is there anyone you think we should approach directly?

**Comment by marcoscaceres** [comment]
Yeah :( I don't know who to recommend, to be honest. I can maybe pick it up again next year.

**Comment by LJWatson** [comment]
It would be good if you can. Will send cake if it'd help?

**Comment by marcoscaceres** [comment]
It won’t. Mounir will want some and I don’t like to share.

**Comment by mounirlamouri** [comment]
I've changed a bit how I handle github emails so I should be slightly more responsive. I don't expect this spec to take much of my time so happy to continue editing.

@LJWatson are the issues listed above the CR blockers?

**Comment by LJWatson** [comment]
Thanks @mounirlamouri @marcoscaceres

The issues in the [first comment](https://github.com/w3c/screen-orientation/issues/102#issue-230162067) are the ones we need to resolve before we open the CFC to transition to CR.


Once in CR we'll need to produce an implementation report (evidence that each feature of the spec has at least two implementations). It doesn't look like their are WPT tests for this spec - is that the plan?

**Comment by LJWatson** [comment]
Meantime we should get the WD updated (it hasn't been in about 12 months). @xfq can you help with this?

**Comment by xfq** [comment]
@LJWatson It looks like the WD is [automatically updated](https://github.com/w3c/screen-orientation/blob/gh-pages/.travis.yml).

**Comment by LJWatson** [comment]
@marcoscaceres @mounirlamouri ping for any progress/timeline? Thanks.

**Comment by marcoscaceres** [comment]
@LJWatson, no, sorry :(

**Comment by marcoscaceres** [comment]
Things are progressing smoothly again thanks to @Johanna-hub, so closing. Still hoping we will be CR ready by mid March.
