### ISSUE TITLE
Spec is unclear about how locks work across multiple screens and display context switches

### ISSUE THREAD

**Issue by cynthia** [w3c/screen-orientation#105]
During the TAG review in w3ctag/design-reviews#157 we mentioned a small nit about something that was unclear. (This is different from the issue raised in #101 )

If there are multiple screens in different orientations, and the orientation is locked on one screen - what should happen when dragging the browser window across different displays?

Given the following scenario:
1. Tablet+PC (e.g. Microsoft Surface) device launches web application which locks orientation to portrait.
2. Device is connected to external display (which also supports portrait orientation), which is in landscape orientation.
3. Browser window is dragged to the external display.

It was a bit unclear what would happen in the this context. Is it expected to simply follow platform conventions?

Another scenario where this would kick in is when using a display context switching setup such as Samsung's DeX, where the orientation could be locked to portrait by the active document in phone mode, then when docked it would most likely be in landscape mode - what should happen in this scenario?

It would be nice if it was a bit clearer on how the spec touches on multiple displays.

**Comment by xfq** [comment]
IMHO it should be UA-defined. Different platforms might handle cases like this differently.

**Comment by marcoscaceres** [comment]
Now handled by: 
https://w3c.github.io/screen-orientation/#screen-orientation-change

> When a user-agent determines that the screen's orientation has changed for a [top-level browsing context](https://html.spec.whatwg.org/multipage/browsers.html#top-level-browsing-context), or the user moves the [top-level browsing context](https://html.spec.whatwg.org/multipage/browsers.html#top-level-browsing-context) to a different screen, then run the [screen orientation change steps](https://w3c.github.io/screen-orientation/#dfn-screen-orientation-change-steps) with the [top-level browsing context](https://html.spec.whatwg.org/multipage/browsers.html#top-level-browsing-context)'s [active document](https://html.spec.whatwg.org/multipage/browsers.html#active-document).
