### ISSUE TITLE
Where are terms 'primary' and 'secondary' defined within spec?

### ISSUE THREAD

**Issue by tshinnic** [w3c/screen-orientation#113]
It may be a fault in my education that I do not know what 'primary' or 'secondary' are supposed to mean here, but the specification is not helping by defining these terms.  Somehow the statement
>   However, the user agent can associate *-primary and *-secondary values at will.

is insufficient illumination.

**Comment by mounirlamouri** [comment]
One of the two primary orientation is expected to be the natural orientation of the device. The other primary is really hard to define.

**Comment by xfq** [comment]
MDN has some explanation here: https://developer.mozilla.org/en-US/docs/Web/API/Screen/lockOrientation

(Although `lockOrientation` has been removed from the spec.)

**Comment by xfq** [comment]
> One of the two primary orientation is expected to be the natural orientation of the device. The other primary is really hard to define.

Do you mean that the "primary" in `OrientationType` and in `OrientationLockType` has different meanings?

**Comment by mounirlamouri** [comment]
No, they don't. What makes you think they do?

**Comment by xfq** [comment]
> No, they don't. What makes you think they do?

Because in https://github.com/w3c/screen-orientation/issues/113#issuecomment-361950969 you mentioned "One of the two primary" and "The other primary"...

What are the two "primaries" here? Could you please clarify? Thanks.

**Comment by mounirlamouri** [comment]
`landscape-primary` and `portrait-primary`. One *has* to be `natural`.

**Comment by xfq** [comment]
I see. What about adding some description like the following?

```html
The term <dfn>primary</dfn> represents the orientation of the screen when the
device is held in its natural orientation, or turned by 90° clockwise from its
natural orientation. The term <dfn>secondary</dfn> represents the orientation of
the screen when the device is held 180° from its normal position, or turned by
90° counterclockwise from its natural orientation.

<div class="figure" id="primary-secondary-example">
    <table>
      <tr>
        <td>
          <img alt="'portrait-primary' when the device is held in its natural orientation"
            src="images/portrait-primary.svg">

        <td>
          <img alt="'portrait-primary' when the device is turned by 90° clockwise from its natural orientation"
            src="images/portrait-primary-2.svg">

        <td>
          <img alt="'portrait-secondary' when the device is turned by 180° from its natural orientation"
              src="images/portrait-secondary.svg">

        <td>
          <img alt="'portrait-secondary' when the device is turned by 90° counterclockwise from its natural orientation"
              src="images/portrait-secondary-2.svg">

      <tr>
        <td>`portrait-primary`
        <td>`portrait-primary`
        <td>`portrait-secondary`
        <td>`portrait-secondary`
    </table>
    <p class="caption">Example of the `portrait-primary` and `portrait-secondary` orientation types
</div>
```

(The images are in https://github.com/xfq/testing/tree/master/screen-orientation/images currently.)

Note that I didn't include the `landscape-*` counterparts in the example. IMHO these four images have already explained the basic idea. WDYT, @mounirlamouri?

**Comment by Johanna-hub** [comment]
@xfq I think this description and table is great, I have made some suggested edits to first paragraph  to make it clearer - what do you think?  
Also the images are really useful, but I think portrait-secondary-2 should be flipped the opposite way to portrait-secondary-1 (at the moment they are the same image).
Is it worth writing in the table the natural orientation of the pictured device?
I am torn about the landscape counterparts, I do agree that the portrait images on their own have explained the idea, but also it would be good to have all the options there for reference and it's not too many to add...

`When a device is held in its natural orientation, its orientation is represented either by <dfn>landscape-primary</dfn> or <dfn>primary-portrait</dfn>.  When the device is turned 90° clockwise from its natural orientation, its orientation is represented by the other primary term. 
When a device is turned 180° from its natural orientation, its orientation will be represented by either <dfn>landscape-secondary</dfn> or <dfn>secondary-portrait</dfn>.  When the device is turned 90° counterclockwise from its natural orientation, its orientation is represented by the other secondary term.
`

**Comment by marcoscaceres** [comment]
I'd suggest sending a pull request with the suggestions above. We can then evaluate them inline in the spec.
