### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by xfq** [w3c/screen-orientation#119]
To get to/through CR, we need to have a test suite. This issue tracks the test coverage of the spec.

- [x] [`Screen.orientation`](https://github.com/web-platform-tests/wpt/blob/master/screen-orientation/idlharness.window.js)
- [x] `Screen.orientation.lock()`
- [ ] `Screen.orientation.unlock()`
- [x] [`Screen.orientation.type`](https://github.com/web-platform-tests/wpt/blob/master/screen-orientation/orientation-reading.html)
- [x] [`Screen.orientation.angle`](https://github.com/web-platform-tests/wpt/blob/master/screen-orientation/orientation-reading.html)
- [x] [The `onchange` event handler](https://github.com/web-platform-tests/wpt/blob/master/screen-orientation/onchange-event.html)

- [x] [Update the orientation information](https://w3c.github.io/screen-orientation/#dfn-update-the-orientation-information)
- [ ]  [Apply an orientation lock](https://w3c.github.io/screen-orientation/#dfn-apply-an-orientation-lock)
- [ ]  [Lock the orientation](https://w3c.github.io/screen-orientation/#dfn-lock-the-orientation)
- [ ]  [Determine the active orientation lock](https://w3c.github.io/screen-orientation/#dfn-active-orientation-lock)
- [ ] [Handle angle/visibility changes](https://w3c.github.io/screen-orientation/#handling-screen-orientation-changes)

Which part of these are testable, and has tests? What else do we need?

/cc @marcoscaceres @mounirlamouri

**Comment by marcoscaceres** [comment]
We have [WPT](https://github.com/web-platform-tests/wpt/tree/master/screen-orientation) - but need to go through them and match them to the above. 

The interface is tested also: https://github.com/web-platform-tests/wpt/blob/master/interfaces/screen-orientation.idl

What's more useful is to see if the algorithms have been well tested. I believe they have been, but one of us has to sit down and run through all the tests and spec line by line.

**Comment by marcoscaceres** [comment]
(we also need to produce a the report)

**Comment by marcoscaceres** [comment]
Could we update the checklist above to include the algorithms?

**Comment by xfq** [comment]
We have:

* [Update the orientation information](https://w3c.github.io/screen-orientation/#dfn-update-the-orientation-information)
* [Apply an orientation lock](https://w3c.github.io/screen-orientation/#dfn-apply-an-orientation-lock)
* [Lock the orientation](https://w3c.github.io/screen-orientation/#dfn-lock-the-orientation)
* [Determine the active orientation lock](https://w3c.github.io/screen-orientation/#dfn-active-orientation-lock)
* [Handle angle/visibility changes](https://w3c.github.io/screen-orientation/#handling-screen-orientation-changes)

Any other algorithms?

**Comment by marcoscaceres** [comment]
That looks like all of them. Moved them to the top. @xfq, Mounir and I are planning to get together during TPAC to try to finish off the spec.

**Comment by xfq** [comment]
Thank you!

**Comment by marcoscaceres** [comment]
Rechecked every assertion. Everything is now tested.
