### ISSUE TITLE
lockOrientation() returning Promise when no orientation change will happen is unclear

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/screen-orientation#12]
We could fix that by basically say that if the current orientation is part of orientations, return a resolved promise...

**Comment by marcoscaceres** [comment]
I think that makes sense. The condition is met so "then" you can continue.

**Comment by mounirlamouri** [comment]
See https://github.com/w3c/screen-orientation/pull/19

**Comment by mounirlamouri** [comment]
Fixed per #19
