### ISSUE TITLE
Send events before promise resolve

### ISSUE THREAD

**Issue by kenchris** [w3c/screen-orientation#120]
An annoyance with the orientation lock API, is that the promise resolves before the event is sent.

This makes it hard to default handlers that you don't want to call in certain cases, because if you remove the handler then there is no good place to add it back in, because if you do after the promise gets resolves, it might get called as the event is still pending :-( 

This also means that it makes sense for the unlock to return a promise.

We ran into this in https://github.com/intel/generic-sensor-demos/issues/72

**Comment by marcoscaceres** [comment]
I think this makes sense. Essentially, we need to queue a task to first dispatch, then resolve.
