### ISSUE TITLE
cordova-plugin-screen-orientation does not work

### ISSUE THREAD

**Issue by r4-2017** [w3c/screen-orientation#123]
I need help from someone! I try use the plugin above with code: 
```JS
function fixpositionscreen(){
	try{
		alert('trying...');
		if (screen.orientation.lock('portrait-primary')) { alert('yes, it was blocked');}
		else {alert('no, it was not blocked....');}
	}
	catch(err){
		alert(err);
	}
}
fixpositionscreen();
```
So, I receive message saying: "yes, it was blocked' but the screen is not locked. Help me.
PS: SO   is Android
Cordova/Phonegap 8.0
Using phonegap serve command for provider server of application

**Comment by Honry** [comment]
`screen.orientation.lock()` is a Promise, which will always return a Promise object, i.e. it will be always `true` in your `if` condition.
You should use `Promise.then()....catch()` instead of `try..catch`, or `async/await` with `try...catch`.

**Comment by marcoscaceres** [comment]
So, as @Honry said, using async/await:

```JS
async function fixpositionscreen(){
	try {
		alert('trying...');
		if (await screen.orientation.lock('portrait-primary')) { 
                     alert('yes, it was blocked');
                }
		else {alert('no, it was not blocked....');}
	}
	catch(err){
		alert(err);
	}
}
fixpositionscreen();
```

**Comment by Honry** [comment]
@marcoscaceres, the `lock` promise will resolve with `undefined`, and actually we don't need `if...else` at all.
```
async function fixpositionscreen(){
	try {
		alert('trying...');
		await screen.orientation.lock('portrait-primary'));
                alert('yes, it was blocked');    
	}
	catch(err){
                alert('no, it was not blocked....');
		alert(err);
	}
}
fixpositionscreen();
```
@r4-2017, you can use the [`onchange`](https://w3c.github.io/screen-orientation/#dom-screenorientation-onchange) event handler to monitor actual orientation change.

**Comment by marcoscaceres** [comment]
heh, yeah... I should have checked that :) It's been a while. Would be cool to maybe add something like this to the spec.

**Comment by Johanna-hub** [comment]
@marcoscaceres Could this go into Section 6. Examples?

**Comment by marcoscaceres** [comment]
yeah, it could. But we'd want to get rid of the alerts and do `console.log();` instead... and check it actually works.

**Comment by marcoscaceres** [comment]
@Johanna-hub given the example rewrite, could you check if the current examples cover this case? If you think it's covered, feel free to close this.

**Comment by Johanna-hub** [comment]
Yes, this is now covered by example 1.
