### ISSUE TITLE
OrientationInformation should be a dictionary

### ISSUE THREAD

**Issue by domenic** [w3c/screen-orientation#13]
It is not a constructible class, and has no methods or `this`-dependent constructs, and so should just be a normal JavaScript object (i.e. "dictionary" in WebIDL terms).

**Comment by mounirlamouri** [comment]
I entirely agree with you. @marcoscaceres did the same suggestion.

However, the WebIDL spec says:

> Dictionaries must not be used as the type of an attribute, constant or exception field.

It might not make a lot of sense but going against the spec sounds a bit painful. I should probably ping heycam to know why this is there. I am especially intrigued because it seems that we could return a Dictionary from a function call but not return it from a readonly attribute.

**Comment by domenic** [comment]
Oh my goodness. That seriously hurts web spec usability. We should get that fixed ASAP in WebIDL. @heycam! Help us!

**Comment by heycam** [comment]
It's not as simple as lifting the restriction, unfortunately. Dictionary values, like sequences, are "copy-by-value" kind of things, not object references. If we just lift the restriction on IDL attribute types, then each time you get the property you would get a newly created object for the dictionary value. This would make `screen.orientation != screen.orientation`, which I think is something we want to avoid.

We have some ideas for solving this for array-ish types (although nothing completely satisfying yet), and hopefully we can use the same solutions for dictionary-ish types too. Expect an email discussing options either tomorrow, or in a month's time (more likely) after I'm back from my leave.

**Comment by domenic** [comment]
Can't we just make them normal JavaScript objects? Why do they have to get new pass-by-value semantics?

**Comment by heycam** [comment]
Currently Web IDL handles conversion of JS objects to IDL dictionary values when you pass in an object to something expecting a dictionary, and also handles the creation of objects that represent dictionary values when they are returned back to JS. One of the reasons for handling these things was the estimation that spec authors would otherwise end up inspecting properties on dictionary objects and would forget or be unprepared for exceptions that would be thrown. Handling the property lookups all up front for the spec author avoids that problem.

Those concerns obviously don't apply in this case, where we're only returning things to JS.

So yes the solution for `screen.orientation` should be for them to be normal JS objects, but I'm not sure changing all existing uses of dictionaries is the right way to do that.

Gecko has a `[Cached]` extended attribute that can be put on IDL attributes which allows them to have sequence types (and this could extended to dictionary types too). It effectively means that they're reference types, and code explicitly clears the "cached" JS value so that the next time the property is got a new value will be returned. Something like this (though I'm not fond of the way an extended attribute changes the behaviour so much), or some other syntax that means you have a reference to an object rather than a value that is copied sounds like the right thing to do.

**Comment by domenic** [comment]
Maybe just `object` instead of `dictionary`.

**Comment by heycam** [comment]
That's how you would need to do it now; use `object` and write in prose exactly how to construct the JS object. You lose the ability to describe the shape of the object in the IDL and get the object constructed in a consistent way for free (create a new object as if by `{}`, call `[[Put]]` on the object with these values, then call `[[Put]]` on the object with these values, etc.).

**Comment by domenic** [comment]
Ah OK, well at least that helps unblock screen orientation.

**Comment by heycam** [comment]
OK. (Sorry didn't mean to block by saying "please wait for a month".) I hope in the near future we get a solution that will allow you to rip out the manual object construction stuff.

**Comment by heycam** [comment]
You could actually invoke the "convert IDL dictionary value to JS value" algorithm (the second half of http://heycam.github.io/webidl/#es-dictionary) yourself manually at the point you need to create the object, and then use the result as the `object`-typed IDL attribute value.

**Comment by mvano** [comment]
I discussed some of this with Mounir in person but would like to get your opinion on this. To the best of my understanding, the following behavior is desirable:
1. screen.orientation is a live object so that if you alias it and orientation changes later, you can read  the updated values from the alias as per normal javascript object references
2. screen.orientation == screen.orientation just as screen == screen
3. The value given to the promise of screen.lockOrientation is a frozen snapshot of the state resulting from the lockOrientation call, so value != screen.orientation because it is not the same object even though its attributes may have the same values

Is that correct? If so, my impression is that the behavior described above is incompatible and that worries me.

**Comment by abarth** [comment]
This thread doesn't state a problem that we're trying to solve.  Is there any benefit to making this change?  Having an API described in prose rather than in IDL has a cost because user agents are less likely to implement the prose interoperably.  It sounds like the motivation for this change is just aesthetics, in which case I would recommend not making this change.

**Comment by domenic** [comment]
(Please excuse me if I say something incoherent, contradictory, or that breaks some constraints we have been trying to preserve; I'm just settling back into this thread after a few months off and haven't quite reminded myself of the problem space.)

@abarth: The problem is creating and using classes (especially non-constructible ones) for things that are just data, not data and behavior. Things with no `this`-dependence, in other words. This brings along a host of unfortunate behaviors, such as the inability to make a faithful copy of the object, it not being recognized as a "plain object" by various utility libraries (jQuery among them), it not outputting nicely in various unit-testing frameworks which are afraid to trigger getters, it not outputting in the watch window of at least some web inspector tools, and so on.

The fact that WebIDL sucks at this is simply a problem to be fixed with WebIDL, stemming from its historical OMGIDL-origins. I can work on fixing WebIDL in this regard if that would be helpful, now that it is part of my day-job description.

@mvano: I don't _think_ I ever stated your point 3. Although I can't remember why we want the promise to resolve to anything anyway (why not just make the user check `window.screen.orientation`?), if we do, we can just make it resolve to `window.screen.orientation`.

To be clear, what I am proposing (modulo my first-paragraph disclaimer) is:

``` js
window.screen.orientation = { type: "portrait-primary", angle: 0 };

function internalBrowserFunctionCalledWhenTheUserRotatesTheirScreen() {
    window.screen.orientation.type = "landscape-primary";
    window.screen.orientation.angle = 90;
}
```

**Comment by mounirlamouri** [comment]
@domenic, do you expect window.screen.orientation to always be the same object with .type and .angle sometimes returning different values or do you expect the underlying object to change when the orientation changes?

**Comment by domenic** [comment]
@mounirlamouri I could go either way, but I think having it the same object works just fine (as I showed above). It would only need to change if you wanted to make the properties non-writable, which is itself somewhat non-idiomatic.

**Comment by abarth** [comment]
What happens if we want to add some this-dependent functionality to this object in the future?

**Comment by domenic** [comment]
Well, leaving aside that the entire design of the object seems against that (it being basically a tuple and all, only one step away from a string), you can then upgrade it to a class instance if necessary, which will lose the benefits of being a plain object. Or you can just leave it a plain object---those can have `this`-dependent functionality as well; the only reason we normally use classes for such cases is because the prototype approach saves memory, but that is not a concern with a literal singleton.

**Comment by domenic** [comment]
Oh, another problem with the getters-on-instances approach is that `Object.keys(window.screen.orientation)` would give `[]`, since it would have no own-properties. (This is what is behind many of the failures I mentioned for e.g. shallow object copying, introspection, and so on.)

**Comment by mounirlamouri** [comment]
@domenic I would prefer to make the property non-writable because it might confuse developers if you can do `window.screen.orientation.angle = 270;` because it will **not** change the screen orientation angle to 270.

**Comment by abarth** [comment]
I agree that we should make the object constructible.

The problems you cite with jQuery apply generically to everything in the web platform.  Wouldn't it be better to fix those tools to work well with every interface in the platform?  If we take the approach you're suggesting, we'll have to break them all anyway if we decide to add this-dependent functionality to this object in the future.  If we improve the tools to work with every interface in the platform, they'll work well with every interface in the platform.

We're not smart enough today to know that we'll never want to extend this object in the future.  I don't feel comfortable foreclosing that option.

**Comment by domenic** [comment]
@mounirlamouri That's a fair point, although I know most of my fellow TAG members would call it a non-problem and say "if the user wants to overwrite random stuff, they should be able to." But to make it work, you should then update `window.orientation` when it changes. Revising my above example:

``` js
window.screen.orientation = Object.create(Object.prototype, {
  type: { value: "portrait-primary", enumerable: true, configurable: true },
  angle: { value: 0, enumerable: true, configurable: true }
});

function internalBrowserFunctionCalledWhenTheUserRotatesTheirScreen() {
  window.screen.orientation = Object.create(Object.prototype, {
    type: { value: "landscape-primary", enumerable: true, configurable: true },
    angle: { value: 90, enumerable: true, configurable: true }
  });
}
```

(You can see how this is not really very idiomatic. Even most APIs written by JS developers that expose features in this way do not bother to make them nonwritable.)

@abarth The majority of my reply was explaining why this does _not_ foreclose extending the object in the future.

**Comment by abarth** [comment]
@domenic Should we then use this approach for every object in the platform, including those that have this-dependent functionality?  Perhaps we should only use it for those objects that historically didn't have this-dependent functionality but grew it at a later date.

**Comment by mounirlamouri** [comment]
@domenic just to make sure I have a comprehensive understanding of your proposal. When we discussed on IRC last week, you suggested to resolve lockOrientation() promise using screen.orientation. However, based on one of your comment above, it seems that I might have misunderstood. Do you not agree with resolving the promise with something at all? Could we just resolve the promise with a new instance?

**Comment by domenic** [comment]
@mounirlamouri 

> Do you not agree with resolving the promise with something at all? Could we just resolve the promise with a new instance?

I can't remember why I thought it would be useful. Was there some scenario in which it would different from the user just looking at `window.screen.orientation` themselves? I guess knowing the answer to that would help with the second question about new instances.

@abarth Objects that are instances of classes should be instances of classes. Objects that are not should not be.

**Comment by abarth** [comment]
@domenic That argument is circular.  The question we're deciding is whether this object ought to be an instance of a class.  More specifically, we're deciding whether the set of objects that represent screen orientations ought to be reified as the class ScreenOrientation.

**Comment by domenic** [comment]
Exactly. Perhaps we could ask the spec editors? Was the intention for this to be a [class](http://en.wikipedia.org/wiki/Class_%28computer_programming%29), or a [record](http://en.wikipedia.org/wiki/Record_%28computer_science%29)?

**Comment by abarth** [comment]
If they said that the intention was for this to be a class, would that satisfy you?

**Comment by domenic** [comment]
Yes, certainly. If OrientationInformation was meant to be "an extensible template for creating objects, providing initial values for state (member variables) and implementations of behavior (member functions, methods)", I would be surprised, and would prefer some justification, but at some level I'd have to accept they know the problem domain better.

**Comment by abarth** [comment]
IMHO, all interfaces in the web platform should be designed for extensibility given that we're constantly extending the platform.

Rather than foreclosing future extensibility in the platform, we should get folks to fix their unit testing frameworks to work well with the hundreds of interfaces that already exist in the platform.

**Comment by mounirlamouri** [comment]
OrientationInformation was meant to be a record. Basically, it is screen.orientaiton.{angle,type} but it could have been screen.orientationAngle and screen.orientationType. The .orientation is between is mostly to make it more javascript-y.

**Comment by abarth** [comment]
@mounirlamouri On what basis do you claim that OrientationInformation was meant to be a record?

**Comment by domenic** [comment]
Thanks @mounirlamouri, that helps reinforce the reply I was about to make to @abarth. Which is that while I agree with your larger point, Adam, at some level you have to say that you're just using language features, not doing object-oriented design. We don't say "we should use an array of characters instead of a string, since then we can extend it with methods later!" We just use a string. Similarly, we can just use plain object records, without feeling like we're being anti-extensibility.

**Comment by mounirlamouri** [comment]
> @mounirlamouri On what basis do you claim that OrientationInformation was meant to be a record?

@domenic asked for the editor intentions. Edit: I'm the editor.

**Comment by abarth** [comment]
@mounirlamouri You can't imagine anyone in the future wanting to extend this object with this-dependent functionality?

**Comment by mounirlamouri** [comment]
I can't speak for what other people might want to do in the future. However, the object returned by `screen.orientation` is meant to describe the screen's orientation and I can't think for many ways to describe a screen orientation. Can you think of any addition that would be this-dependent and still fulfil the role of the object?

**Comment by abarth** [comment]
I don't think we're smart enough to predict the future, which is why we're fortunate that the web platform is designed for extensibility.

**Comment by mounirlamouri** [comment]
@annevk @bzbarsky WDYT?

**Comment by bzbarsky** [comment]
I have no particular opinions on this specific object, though I do think we want to avoid the API design where we mutate a value property on a vanilla object, because that suddenly involves defining what happens when someone has reconfigured it to be non-writable and so forth.

**Comment by annevk** [comment]
I found an example that seemingly supports @abarth. http://www.w3.org/TR/2011/WD-cssom-view-20110804/#caretposition could have been an object. However, nowadays it has a method on it: http://dev.w3.org/csswg/cssom-view/#the-caretposition-interface

@domenic what would the compatibility story have been here?

**Comment by domenic** [comment]
@bzbarsky good point; that's another point against my original version and for my second version.

@annevk the compatibility story would have been that we upgraded it to a class, and everything would be fine. (And yes, it is a theoretical back-compat hazard---in the same way changing `Object.prototype.toString.call(document.body.getBoundingClientRects()[0])` from `[object ClientRect]` to `[object DOMRect]` is.)

But even then, it's unlikely we would have called that a record, because it has some pretty clear internal state (the "associated caret node, caret offset, and caret range"). If you tried to implement those in JS, you would pretty quickly discover you have to store that internal state somewhere.

Again, I'm not saying that we should use records everywhere and not ever use classes. I'm just saying that we should be able to recognize when something is designed to be a record, and use records in those cases, instead of getting into a Kingdom of Nouns situation where everything needs to be a class instance because maybe in the future it will transform from a record to a class. I think the boundary between these two concepts is pretty clear, and in the vast majority of the cases, proper design work will end up deciding on one ahead of time and not changing (in either direction) in the future. "Extensibility" doesn't mean "future-proofed for bad design."

And remember---literally the only reason we're putting these in an object of any sort is to avoid typing `window.screen.orientationAngle` and `window.screen.orientationType`. We could sidestep this whole debate and do that, effectively admitting that objects-as-records are unusable in the web platform and we must resort to namespacing properties. Or ... we could use objects-as-records.

**Comment by abarth** [comment]
> the compatibility story would have been that we upgraded it to a class, and everything would be fine

If everything would be fine, then that means authors won't notice the difference and we might as well use a class from the beginning.  Except everything won't be fine.  We'll break all the jQuery and unit testing integrations that you claim are the benefits of this approach.

> I think the boundary between these two concepts is pretty clear,

That's the core of the disagreement.  Whether some particular thing is a record or a class is something we're likely to want to change over time as the platform evolves.  We've done it before.  We'll do it again.  If we use records, we'll need to make a breaking change to the platform instead of just gracefully extending the interface.

> Or ... we could use objects-as-records.

Or we could just use interfaces, like we've been doing happily for 20 years.

**Comment by marcoscaceres** [comment]
On IRC, @mounirlamouri proposed we change the API to:

``` JS
partial interface Screen {
    readonly    attribute ScreenOrientation orientation;
};

interface ScreenOrientation : EventTarget {
    Promise<undefined> lock (OrientationLockType orientation);
    void               unlock ();
                attribute EventHandler    onorientationchange;
    readonly    attribute OrientationType type;
    readonly    attribute unsigned short  angle;
};
```

This resolves a whole bunch of weirdness, including: 
- it's a class! :+1: ... no more dealing with weird dictionaries, etc. 
- removes `onorientationchange` on the `<body>` element.
- puts the event handler on a predictable place.
- Makes API much more logical and keeps it extensible 

``` JS
screen.orientation.lock('landscape').then(doWhatYouGottaDo, boo)
screen.orientation.addEventListener("orientationchange", (e)=>{
    alert("Screen orientation state is now " + e.target.type)
    screen.orientation.unlock()
}));
```

How's that sound? I'm updating the spec to match.

**Comment by domenic** [comment]
+1, although perhaps orientation.onorientationchange is a bit redundant? No big deal though.

**Comment by marcoscaceres** [comment]
@domenic, good catch. Will change to `onchange`.

**Comment by mounirlamouri** [comment]
I think we reached an agreement. I'm closing this issue.

**Comment by marcoscaceres** [comment]
Reopening so we can close it with a PR
