### ISSUE TITLE
Canonical orientation

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/screen-orientation#14]
Elsewhere, @larsgk wrote: 

> 1. decide on ONE (either portrait or landscape) "0 degree rotation" =
>    "device up" that will trickle through all specs relating to orientation.
>    In practice, this would mean that lockOrientation("0deg") ~
>    (x,y,z)=(0,1,0) , where lockOrientation could be an async request telling
>    if the angle was allowed, etc. - e.g. more options could be given
>    ("0deg,180deg") and maybe "180deg" is set and returned...The important
>    thing here is that the developer has a consistent way of mapping the locked
>    orientation to the data coming from the accelerometer.

**Comment by mounirlamouri** [comment]
Should be handled by https://github.com/w3c/screen-orientation/pull/18

**Comment by mounirlamouri** [comment]
Should be fixed by #18 please reopen if you disagree.
