### ISSUE TITLE
Clarification regarding locking the screen orientation

### ISSUE THREAD

**Issue by Johanna-hub** [w3c/screen-orientation#143]
In the section regarding locking the screen orientation, the spec currently state:

> If the user agent supports locking the screen orientation, it MUST allow the screen to be locked to all of the states of the OrientationLockType enum. 

@mounirlamouri I was hoping you could please clarify this statement for us.  Does this really mean that the screen must be able to be locked to all of the following: `any, natural, landscape, portrait, portrait-primary, portrait-secondary, landscape-primary, landscape-secondary? `

**Comment by mounirlamouri** [comment]
It's been a while so I will mostly try to guess what I meant and why. For what I can tell, I think your description is correct: all types must be supported or none. My interpretation is that this was added to avoid pages locking to `landscape` and having to guess whether it worked out or not. If this is a problem, we could always add text to have the method reject.

**Comment by Johanna-hub** [comment]
@mounirlamouri Great, thank you so much for the explanation 🙂

**Comment by marcoscaceres** [comment]
closing as answered.
