### ISSUE TITLE
Definition of default orientation

### ISSUE THREAD

**Issue by Johanna-hub** [w3c/screen-orientation#150]
Currently default orientation is defined with the following:  

```
        A <a>document</a>'s <dfn>default orientation</dfn> is the set of
          orientations to which the screen orientation is locked when it is not
          explicitly locked by this API or any other means.
```
It would be great to get some clarification on why default orientation is a set?  From looking at the android docs it looks like the system decides on one orientation if none is specified.

@mounirlamouri Could you please explain this further?

Relates to https://github.com/w3c/screen-orientation/issues/104

**Comment by mounirlamouri** [comment]
The default orientation is indeed system-specific. For example, on most Android phones, the default orientation is landscape + portrait-primary (IIRC) but it can be changed to be portrait-primary only. We could expose this information in the API but at the time we didn't want to. FWIW, Chrome's media controls use this information (if portrait-primary only) so it may make sense to expose this to the Web so websites can also implement logic that are based on the default orientation.

**Comment by Johanna-hub** [comment]
I think this could make sense because at the moment the definition is a bit vague, but exposing the information would make it very useful.

@marcoscaceres What do you think?

**Comment by marcoscaceres** [comment]
If we can get the defaults from the OS, and assuming they don't change, it could be good to expose them.  However, exposing these does add to device fingerprinting ... as the array's values will be device specific (though not particularly varied from one device to another). 

@mounirlamouri, how do you use the defaults in the media controls? (looking for the use case, basically).

**Comment by marcoscaceres** [comment]
Rethinking this, the "set" should go away, as unlocking just leaves it to the UA/OS to handle the orientations (whatever those may be).

**Comment by marcoscaceres** [comment]
The orientations really represent the orientations to which a user can then change by rotating the device. So, landscape really means that the user can change the orientation to either landscape primary and landscape secondary, but not any portrait orientation. 


I'm going to redefine things in those terms.

**Comment by marcoscaceres** [comment]
Respecified in latest draft.
