### ISSUE TITLE
Deprecate angle?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/screen-orientation#162]
@Johanna-hub has been doing some testing and we are seeing unreliable result with `angle`... I wonder if angle is just going to turn into another "device orientation" disaster where different browsers on different devices (or even the same devices) end up reporting different things for the angle? Also, is there any value or use case for the angle? What would people use it for? (they can use gyroscope API or whatever instead, no?)

@mounirlamouri thoughts?

**Comment by Johanna-hub** [comment]
I have been testing that the primary and secondary orientations and associated angles match with different results on Firefox and Chrome.  The web platform test is here https://github.com/web-platform-tests/wpt/pull/15429

I have been testing on my phone.  The test checks that portrait-secondary angle is 180, that landscape-primary is either 90 or 270 and landscape-secondary is the angle left over.

When I run the tests in Firefox, sometimes the angles are exactly right, but running the tests multiple times - the angle can get "stuck" and doesn't change.

In Chrome, the results are variable, I have had some where all 3 angles are right but more often 2 out of 3 are right or more random results.

Would be great to hear thoughts.  Also this is the new table in the spec where the primary/secondary orientations and angles are explained, in case you have any comments on that https://w3c.github.io/screen-orientation/#reading-the-screen-orientation

**Comment by mounirlamouri** [comment]
The main use cases of angles is to be used when doing some computation for rendering IIRC.

**Comment by marcoscaceres** [comment]
@kenchris would appreciate any thoughts you have here... specially in light of the gyro API and from a rendering perspective? I can’t think of anything personally.

**Comment by Johanna-hub** [comment]
Orientation/angle tests now merged and here https://github.com/web-platform-tests/wpt/blob/4950b69ed6774f1b97c41a5daddf7bfa2327372e/screen-orientation/orientation-reading.html#L25

Now that they have been merged and I can run on my phone, Firefox is consistently passing and Chrome is failing

**Comment by marcoscaceres** [comment]
CC'ing @anssiko also... as current editor of Gyro spec... might have a good perspective to share here. Core question: maybe we can deprecate `angle` on this API in light of Gyro spec?

**Comment by anssiko** [comment]
What are the key use cases for `angle`? Computation for rendering is a bit vague.

Depending on the use cases, [`OrientationSensor`](https://w3c.github.io/orientation-sensor/) might be able to help. Nudging my esteemed co-editor @kenchris.

That spec uses the [reference frame](https://w3c.github.io/accelerometer/#reference-frame) concept that provides web developers a knob to define whether the local coordinate system for orientation is relative to the device (stationary) or screen (can rotate).

**Comment by marcoscaceres** [comment]
`OrientationSensor` sounds event better, specially given the reference frame.

**Comment by marcoscaceres** [comment]
Closing, at it's been around too long to deprecate. It's still really unreliable by the looks of it.
