### ISSUE TITLE
Page visibility transition can fire when false/true/false happens within a frame

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/screen-orientation#179]
Due to how the Page Visibility transition portion of https://www.w3.org/TR/screen-orientation/#Screen-orientation-change is written, if a transition from NOT VISIBLE to VISIBLE to NOT VISIBLE happens within a frame, the processing model will currently deliver an event.

I advise adding a new step 1 which exits if the page visibility is NOT VISIBLE.

**Comment by marcoscaceres** [comment]
@toddreifsteck can you help me integrate with https://github.com/w3c/page-visibility/pull/50 ? That will give us the hooks for "visible" and "hidden". Would appreciate a pull request on this spec once that lands to fix the issue you describe above.

**Comment by toddreifsteck** [comment]
Slammed for next few days. Assigning this to myself for TODO next week.

**Comment by marcoscaceres** [comment]
Understood. I'm the same. We got time tho :) If I get time, I'll try to slap something together and ping you.

**Comment by marcoscaceres** [comment]
Now handled in the spec. This should also be handled once the visibility stuff moves to HTML.
