### ISSUE TITLE
Specification status report for TPAC 2019

### ISSUE THREAD

**Issue by LJWatson** [w3c/screen-orientation#185]
Please can you respond to this comment with a brief specifications status report for the WebApps meeting at TPAC. The report should address the following:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?
* What do you want to achieve for your spec in the next two days (of breakout sessions)?

We're tracking these status reports in [WebApps issue #19](https://github.com/w3c/webappswg/issues/19)

Thanks.

**Comment by marcoscaceres** [comment]
> What progress has your spec made in the last 12 months?

 * overhauled much of the spec to clarify various algorithm and examples - thanks to @Johanna-hub.  
 * added a significant number of [web platform tests](https://w3c-test.org/screen-orientation/), and linked to within the spec - again, thanks to @Johanna-hub. However, we still need to go through #119 and check what's missing. 

> Is anything blocking your spec from moving to CR?

Bugs and things that need discussion:

 * lock() should not fail if another lock() is called in the change event #184
  - related: double check lock(), event, re/unlock() behaviors #151
 * Promise for unlock()? #104 
 * unlocking during event dispatching is undefined #173
 * Reliability of angle #162

Cross spec integration. In particular the following need a bit of work: 

 *  [Deal with fragment navigation](https://github.com/w3c/screen-orientation/issues/87)
 *  [Clarify in which animation frame task events are fired](https://github.com/w3c/screen-orientation/issues/97)
 * [Improve hooks with Page Visibility.](https://github.com/w3c/screen-orientation/issues/77)
 * [Link Screen Orientation with Fullscreen more cleanly](https://github.com/w3c/screen-orientation/issues/62)
 * [Clarification on animation frame task](https://github.com/w3c/screen-orientation/issues/136)
 * [Page visibility transition can fire when false/true/false happens within a frame](https://github.com/w3c/screen-orientation/issues/179) 
 * Clarify how to initialize the screen orientation #145 

I labelled the above "[cross doc](https://github.com/w3c/screen-orientation/labels/cross-doc)". These are not really blocking or preventing interop. 

> If yes, what is your plan to unblock it and do you need any help?

Chair can probably help by seeing if we can get the Safari folks onboard. 
 
iOS supports: 
 * Face up and face down #168 

> What do you want to achieve for your spec in the next two days (of breakout sessions)?

@mounirlamouri and I need to sort out the blocking stuff, assuming we get some time together during TPAC.

**Comment by marcoscaceres** [comment]
Closing as answered.
