### ISSUE TITLE
Heads up: refs to `pagevisibility` (external now visibile) about to be removed

### ISSUE THREAD

**Issue by noamr** [w3c/screen-orientation#205]
See https://github.com/w3c/page-visibility/pull/73
Most of the page visibility spec is moving into the HTML Spec (see https://github.com/whatwg/html/pull/7153), and calls are to be made explicitly instead of the "hook" (`external-now-visible-algorithm`).

Since this spec appears to rely on this ref, opening this issue to track switching to being called directly.

**Comment by noamr** [comment]
https://html.spec.whatwg.org/#page-visibility-change-steps

**Comment by saschanaz** [comment]
That PR https://github.com/w3c/page-visibility/pull/73 is closed without merging, why is that?

**Comment by noamr** [comment]
> That PR [w3c/page-visibility#73](https://github.com/w3c/page-visibility/pull/73) is closed without merging, why is that?

Oops, will add a comment. See [this](https://github.com/w3c/browser-specs/pull/425) and [this](https://github.com/whatwg/html/pull/7238).

PageVisibility has been folded into HTML, and there is a [specific place](https://html.spec.whatwg.org/#page-visibility-change-steps) in the HTML spec to notify other specs of the visibility state change.

**Comment by marcoscaceres** [comment]
Now all updated to use HTML's definition.
