### ISSUE TITLE
Angle not consistently implemented 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/screen-orientation#247]
Over on WebKit, we got a [bug report](https://bugs.webkit.org/show_bug.cgi?id=254863) that `.angle` (and `.type`) are not reported in an interoperable manner.

Using https://krpano.com/ios/bugs/ios164-screen-orientation/ and turning the device clockwise (there are helpful screenshots there too). 

@karlcow did some testing and found:

Firefox Nightly 113 Android 13
screen.orientation.angle: 270
screen.orientation.type: landscape-primary

Chrome Canary 113 Android 13
screen.orientation.angle: 270
screen.orientation.type: landscape-secondary

Safari 16.4 iOS 16.4
screen.orientation.angle: 90
screen.orientation.type: landscape-primary

The spec and the tests agree with Webkit, but we may have a web interop issue at hand. 

Should we change the spec to use counter clockwise values instead? 

@makotokato, wdyt? It would be great if Firefox also reported "landscape-secondary" in this case.

**Comment by makotokato** [comment]
> @makotokato, wdyt? It would be great if Firefox also reported "landscape-secondary" in this case.

I guess that this depends on Android version. (Android 11+ has a lot of changes for window manager of Android, so it seems to be incorrect on some device). I will fix it.

**Comment by marcoscaceres** [comment]
Ok, I guess I should flip the order for the `.angle`s also to match Android in this case. That should also remove some weirdness from the spec, where it could return either 90 or 270.

**Comment by marcoscaceres** [comment]
Ok, sent a PR: https://github.com/w3c/screen-orientation/pull/248 ... other folks watching this, can you please also take a look to make sure everything is right?
