### ISSUE TITLE
determining the active orientation lock

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/screen-orientation#25]
The spec says: 

> 1. If there is only one top-level browsing context with a Document that is visible per [PAGE-VISIBILITY], the active orientation lock MUST be the orientation lock that applies to that browsing context.
>    1. Otherwise, if there are more than one top-level browsing context with a Document that is visible per [PAGE-VISIBILITY] but only one of those Documents is focused, the active orientation lock MUST be the orientation lock that applies to that Document's browsing context.
> 2. Otherwise, the active orientation lock SHOULD be the orientation lock of the latest focused Document's top-level browsing context.

This needs to be rewritten to drop the MUSTs and the SHOULD. We can't have a SHOULD as the last step there - it's confusing and leaves the possibility that one could return some wrong value. 

The steps to determine the active orientation lock are as follows:
1. If there is only one top-level browsing context with a Document that is visible per [PAGE-VISIBILITY], return the orientation lock that applies to that browsing context.
2. Otherwise, if there are more than one top-level browsing context with a Document that is visible per [PAGE-VISIBILITY], but only one of those Documents is focused, return the orientation lock that applies to that Document's browsing context.
3. Otherwise, return the orientation lock of the latest focused Document's top-level browsing context.

Also, in the above, the returned values need to be the values from the enum in a list I think.

**Comment by mounirlamouri** [comment]
I had the SHOULD because I don't feel comfortable doing UX requirement that UA will have no issue ignoring. The first two requirements are pretty obvious and there isn't other alternatives. The latests is less trivial and I wouldn't mind having UA implementing this behaviour in another way.

**Comment by marcoscaceres** [comment]
Ok, but there needs to be some kind of default or something. Imagine what
is written there being implemented as a bunch of if statements or a switch
block. The SHOULD there acts as a conditional, but without clarifying what
exactly should be returned... I.e., SHOULD return x, otherwise (finally)
return y (the default).

**Comment by mounirlamouri** [comment]
Let's do the usual trick: `SHOULD return x, otherwise follow the platform conventions.` ;)

**Comment by marcoscaceres** [comment]
See! _this_ is what I'm talking about! :+1:
