### ISSUE TITLE
Use animation frame task

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/screen-orientation#40]
Elsewhere, @annevk chirped: 

> I think screen orientation changes ought to be relayed during the "animation 
> frame task". See http://lists.w3.org/Archives/Public/www-dom/2014JulSep/0061.html for 
> context.

**Comment by marcoscaceres** [comment]
This one screws "Locking the screen orientation" where we "Cancel all tasks in the screen orientation task source.". 

If we were to fix this, we would need to find all tasks related to screen orientation and cancel them one by one.

**Comment by annevk** [comment]
You could group them yourself. Or make sure the animation frame task specifier people provide this functionality.

**Comment by marcoscaceres** [comment]
yeah, I was thinking maybe we add a flag to each task and then say cancel all the tasks that have that flag.

**Comment by mounirlamouri** [comment]
Moving this post-LC. I think it would be interesting but we want to move to last call ASAP. I don't think this issue needs to block this milestone even more given that the animation frame task concept isn't yet clearly defined.

**Comment by mounirlamouri** [comment]
Section 4.4 (Handling screen orientation changes) should probably run in the animation frame task source as soon as it is ready.
