### ISSUE TITLE
Updating orientation values is potentially racy

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/screen-orientation#42]
Elsewhere, @annevk diligently pointed out: 

> "the values of type and angle will be strongly linked" It might be 
> better to talk about the abstract underlying concepts here as type and 
> angle have no values. They have getters. Also, shouldn't these values 
> be updated based on the animation frame task rather then return 
> something when reading them? It seems doing the operation on reading 
> creates racing issues, e.g. no guarantee that obj.angle === obj.angle, 
> and might cause some amount of locking.

**Comment by mounirlamouri** [comment]
Fixed by #68
