### ISSUE TITLE
Use TypeError instead of DOMException

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/screen-orientation#43]
Elsewhere, @annevk inquisitively asked: 

> Rather than using DOMException, can we simply use JavaScript's 
> TypeError? What we want with DOMException hasn't been figured out and 
> using TypeError works just as well. Or are there scenarios here where 
> you want branching based on the exception? That would be interesting 
> to know.

**Comment by marcoscaceres** [comment]
This is probably invalid.

**Comment by mounirlamouri** [comment]
I disagree with @annevk. The current paradigm is to reject Promises with DOMException. We don't really reject for type related issues. Closing.

**Comment by annevk** [comment]
`TypeError` is JavaScript's generic error for all kinds of issues. And what paradigm are you talking about?

**Comment by marcoscaceres** [comment]
@annevk, are you suggesting we just change the spec to, for example:

>  return a Promise rejected with a TypeError whose name (message?) is NotSupportedError and abort these steps.

About the paradigm, it's from @domenic's [Promises guide](https://github.com/w3ctag/promises-guide#rejection-reasons-should-be-errors):

> In particular, for DOM or other web platform specs, this means you should never use DOMError, but instead **use DOMException, which per WebIDL extends Error**. You can of course also use one of the built-in ECMAScript error types.

In this case, we felt that the DOMException clearly conveyed why the promise was rejected instead of a TypeError (as the names of DOMExceptions are fairly clear): "NotSupportedError", "AbortError", and "SecurityError".

**Comment by annevk** [comment]
See Fetch for examples of rejecting a promise with a TypeError. DOMException is a mess and doesn't follow a pattern of the ECMAScript standard library. I would stay clear of it.

**Comment by domenic** [comment]
I think it's good to go for TypeError if you have any ambitions of your spec being part of the ES standard library, or useful in other environments like Node. (Fetch definitely falls in this category IMO.) But DOMException isn't the worst thing in the world and seems OK for this kind of API.

**Comment by marcoscaceres** [comment]
Thanks @domenic. I think we will keep it as "wontfix".
