### ISSUE TITLE
Rename variables to more clearly indicate what is a list

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/screen-orientation#46]
Elsewhere, @annevk pointed out: 

> "If the active orientation lock is not the current orientation lock" 
> how does this work given that at least current orientation lock is a 
> list? (It would help to rename these variables to more clearly 
> indicate what is a list. That might also help avoid such errors.

**Comment by mounirlamouri** [comment]
None of those are a list, I'm going to rewrite some stuff to make things clearer.

**Comment by marcoscaceres** [comment]
Is it maybe that, for instance, "landscape" is really ["landscape-primary", "landscape-secondary"] and so on?

**Comment by annevk** [comment]
Yeah, how are those not lists?
