### ISSUE TITLE
Remove text about what "fullscreen enabled flag" means

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/screen-orientation#48]
Elsewhere @annevk said:  

> "fullscreen enabled flag has been set (i.e., when the document is in 
> fullscreen)" I think you misunderstand the fullscreen enabled flag. It 
> does not mean this.

**Comment by annevk** [comment]
How does removing the parenthetical remove the problem?

**Comment by marcoscaceres** [comment]
Sorry, I literally took your comment to mean that what was in the parenthesis was the problem. I'll have to re-read the fullscreen spec. Might need a few more hints about the problem to fix the issues.

**Comment by annevk** [comment]
No, the fullscreen enabled flag is the problem. It's just a thing that indicates whether or not a document can _potentially_ go fullscreen. It's for the `allowfullscreen` attribute in HTML.

**Comment by mounirlamouri** [comment]
Taking this. I completely overlooked Marcos' patch. I have one ready.

**Comment by marcoscaceres** [comment]
thanks!

**Comment by mounirlamouri** [comment]
Fixed by #60.
