### ISSUE TITLE
Enumerate objects on which events are fired 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/screen-orientation#49]
Elsewhere, @annevk wrote: 

> "Fire a simple event named change at each screen.orientation object." 
> This needs to talk about the actual objects or you need to ensure you 
> talk about resolving this reference before any developer code got a 
> handle on the screen reference, let alone the orientation reference. 
> Typically you would enumerate the objects somehow.

**Comment by marcoscaceres** [comment]
@mounirlamouri do iframes also receive an orientation event? Re-reading the spec, the whole eventing model + interaction with visibility state is a bit messed up in the locking/unlocking algorithms :(  

Can we set some time aside to go through this later this week? I'm struggling to fix this without rewriting a lot of text.

**Comment by mounirlamouri** [comment]
Fixed by #68
