### ISSUE TITLE
Clarify relationship to css-device-adapt

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/screen-orientation#52]
Elsewhere, @dontcallmedom wrote: 

> while I understand there is ongoing discussion on alignments with 
> DeviceOrientation, I'm less clear there is work to ensure consistency 
> with css-device-adapt; in particular, it seems like it would be useful 
> to understand how the two approaches work together when use 
> simultaneously

**Comment by mounirlamouri** [comment]
According to @marcoscaceres, @dontcallmedom wrote that comment above.

I talked with the css-device-adapt spec editor a long time ago and he wasn't interested in changing the spec back in the days. Device Adaptation is anyway compatible for the moment.
