### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/screen-orientation#59]

**Comment by marcoscaceres** [comment]
Which examples are we missing?

**Comment by mounirlamouri** [comment]
I was thinking of moving the examples section at the end and have a couple of different examples using all parts of the API so readers can quickly have a look on how it is used.

**Comment by marcoscaceres** [comment]
Ok, whatever you prefer. 

My 2c: I like specs that have examples as the introduction because I can quickly get a sense of how the API is used and the use cases it addresses.
