### ISSUE TITLE
Link Screen Orientation with Fullscreen more cleanly

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/screen-orientation#62]
It requires @annevk to add some hooks inside the Fullscreen specification.

This issue is not meant to block any release state of the specification but should be fixed whenever the Fullscreen specification will be ready.

**Comment by xfq** [comment]
Are the Fullscreen hooks ready now?

**Comment by mounirlamouri** [comment]
It doesn't look like it.

**Comment by xfq** [comment]
Is there a GitHub issue in Fullscreen (and in Page Visibility, see #77) so that we can properly track it?

**Comment by marcoscaceres** [comment]
Closing in favor of https://github.com/whatwg/fullscreen/issues/202
