### ISSUE TITLE
4.4 Handling screen orientation changes 

### ISSUE THREAD

**Issue by annevk** [w3c/screen-orientation#72]
- Both algorithms listed here lack detail about whether they run asynchronously or not. 
- They are unclear from what task they run.
- They do not queue tasks to synchronize but rather just dispatch events.
- You are monkey patching PAGE-VISIBILITY.

**Comment by mounirlamouri** [comment]
> Both algorithms listed here lack detail about whether they run asynchronously or not.

Will fix that.

> They are unclear from what task they run.

Ideally, that should happen in the animation frame task source but that's not really defined yet and in the purpose of moving to LC, I don't think it's a good idea to depend on unclear concepts. I will add a comment to the animation frame task source issue that we have opened.

> They do not queue tasks to synchronize but rather just dispatch events.

Will fix that.

> You are monkey patching PAGE-VISIBILITY.

I assume you are referring to the second paragraph? To me, it's not really monkey patching, it's mostly a wait to say:

``` js
document.addEventListener('visibilitychange', function() {
  if (document.visibilityState == 'visible') {
    // steps
  }
}
```

**Comment by annevk** [comment]
That is monkey patching... As e.g. if I implemented it that way it would be different if someone overwrote `document.visibilityState`.

As for animation frame task, you should point that out in the specification. It's a disservice to implementers to hide such essential details for the purposes of some silly process you're trying to go through.

**Comment by mounirlamouri** [comment]
> That is monkey patching... As e.g. if I implemented it that way it would be different if someone
> overwrote document.visibilityState.

I will send a feedback to the web-perf mailing list. Can't really do more.

> As for animation frame task, you should point that out in the specification. It's a disservice to 
> implementers to hide such essential details for the purposes of some silly process you're trying to go 
> through.

I opened #75 to do that. Will work on this after the LC milestone.

**Comment by mounirlamouri** [comment]
I opened an issue (#77) about improving how we hook into Page Visibility. I've also sent an email to the web-perf mailing list to request a better hook: http://lists.w3.org/Archives/Public/public-web-perf/2014Sep/0034.html

I will write a patch to use "now visible algorithm". Should be better.

**Comment by mounirlamouri** [comment]
I think all the issues raised here have been fixed or have a follow-up issue.
