### ISSUE TITLE
Improve hooks with Page Visibility.

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/screen-orientation#77]
The Page Visibility specification doesn't provide a clear way to hook into "document becomes visible/hidden". For the moment, the specification is using "now visible algorithm" but it could be improved.

I sent an email about that: http://lists.w3.org/Archives/Public/public-web-perf/2014Sep/0034.html

This is marked as a Future Enhancement because this specification can only hooks into Page Visibility if Page Visibility does the work for that to happen.

**Comment by marcoscaceres** [comment]
Sent PR https://github.com/w3c/page-visibility/pull/54 ... might need a few more things, but need to check.

**Comment by marcoscaceres** [comment]
Closing as Page Visibility spec is not a thing anymore...
