### ISSUE TITLE
Clarify orientation.angle behavior

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/screen-orientation#79]
@sicking wrote: 

> Also, I can't find any normative definition of if orientation.angle 
> should increase or decrease if the user rotates a device 90 degrees 
> clockwise? 
> 
> My bad, I see it now. Given how easy this is to get wrong, it might be 
> worth adding this information more explicitly at the definition of the 
> 'angle' property, or the 'current orientation angle' concept, rather 
> than just buried inside an algorithm.

**Comment by AFBarstow** [comment]
Including a link to Jonas' comment in case someone wants a bit more context: http://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0531.html

**Comment by sicking** [comment]
I don't feel strongly about the exact wording, but maybe something like:

The property indicates how far the user has turned the device counter-clockwise from it's "natural" orientation. When the device is turned is rotated 90 degrees counter-clockwise, and thus the screen compensates by rotating 90 degrees clockwise, this property returns 90.

If the device is rotated 90 degrees clockwise from it's "natural" orientation, and thus the screen compensates by rotating 90 degrees counter-clockwise, this property returns 270.

The value returned by this property is always in the range 0-359. It never returns negative values.

**Comment by richtr** [comment]
> The value returned by this property is always in the range 0-359. It never returns negative values.

Shouldn't the `angle` interval be specified as [0, 360) instead? For reference: http://en.wikipedia.org/wiki/Interval_(mathematics)#Including_or_excluding_endpoints.

**Comment by xfq** [comment]
> Shouldn't the angle interval be specified as [0, 360) instead?

I don't think so, because [angle](https://w3c.github.io/screen-orientation/#screenorientation-interface) is an [unsigned short](https://heycam.github.io/webidl/#idl-unsigned-short).
