### ISSUE TITLE
"Security" condition should be something else

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/screen-orientation#82]
During TPAC, it was pointed out that "security condition" doesn't quite capture the conditions that restrict applying orientation. We should probably change "security" to something else.

**Comment by xfq** [comment]
Would you please elaborate on what "something else" might be? (Labeling this as "future" for now.)

**Comment by marcoscaceres** [comment]
This issue is a bit meh. Closing.

**Comment by marcoscaceres** [comment]
This is still bugging me. Reopening.
