### ISSUE TITLE
The orientation type 'Natural' should only lock to x-primary

### ISSUE THREAD

**Issue by hexalys** [w3c/screen-orientation#83]
The following definition has contradictions, leading to confusion as to what is `natural`:

> natural: Append portrait-primary, portrait-secondary, landscape-primary or landscape-secondary to orientations such as the associated screen orientation angle is 0.

The angle shall never be `0` on a -secondary position. The point of `natural` is to be a unique `0` angle opposite of a `180` reverse angle. Allowing an implementation to lock to `natural`  to `x-secondary` would reduce natural to an orientation as opposed to an angle.

It should definitely not be the same as `any`. A platform convention is most likely to append natural with an 'any' lock anyway. Most importantly, the angle relationship with `portrait-primary, portrait-secondary, landscape-primary or landscape-secondary` cannot change arbitrarily during runtime.

Also how about adding a `current` orientation lock.

**Comment by hexalys** [comment]
@mounirlamouri Any review of this issue yet? Instead it should be:

natural: Append portrait-primary or landscape-primary to orientations such as the associated screen orientation angle is 0.

**Comment by mounirlamouri** [comment]
Thanks for the report @hexalys and sorry for taking so long to reply. PR #84 is fixing this. Feel free to leave a comment there if it doesn't match what you were expecting.
