### ISSUE TITLE
Clarify the meaning of "screen orientation angle"

### ISSUE THREAD

**Issue by tobie** [w3c/screen-orientation#85]
The spec refers to both "screen orientation angle" (SOA) and "current orientation angle" (COA) but never defines the SOA. It seems, from a cursory glance, that both refer to the same thing. If so either linking SOA to the definition of COA, or better yet only using the SOA would help. If these were in fact two different concepts, you need to define SOA somewhere.

**Comment by mounirlamouri** [comment]
Fixed by https://github.com/w3c/screen-orientation/pull/86
