### ISSUE TITLE
Deal with fragment navigation

### ISSUE THREAD

**Issue by smaug----** [w3c/screen-orientation#87]
"Whenever a top-level browsing context is navigated, the user agent MUST lock the orientation of the document to the document's default orientation. " doesn't deal with fragment navigation.

**Comment by smaug----** [comment]
...since I assume fragment navigation shouldn't affect to the orientation lock.

**Comment by annevk** [comment]
Yeah, this should be a hook from within the navigate algorithm, just like the Fullscreen API does it.

**Comment by mounirlamouri** [comment]
Modifying the HTML specification sounds unfortunate especially because I doubt implementations will hook that directly to the navigation algorithm.

Either way, Chrome is actually ignoring fragment navigation. The fact that it is missing from the specification is an oversight. Marcos, feel free to update the spec in a way that pleases @smaug and @annevk, it is probably easier for the three of you to sync.

**Comment by annevk** [comment]
The way I would do this is that you have define a hook that navigate can invoke. Then you define a monkey patch for navigate and file a bug on HTML. Then once HTML is patched you replace the monkey patch with a reference to the HTML navigate algorithm. That way it's sufficiently clear on both sides that these algorithms have an interaction.

**Comment by xfq** [comment]
@annevk Any progress on the hook from within the navigate algorithm?

**Comment by xfq** [comment]
(Labeling this as "future" for now.)

**Comment by annevk** [comment]
@xfq typically those monkey patches work on the hooks. File an issue against the HTML Standard with some sense of the priority?

**Comment by Johanna-hub** [comment]
We are currently looking at how to test the Active orientation lock algorithm and have two questions, that it would be great to have some clarification on, (we have looked at Fullscreen spec and unable to find the answers there either).  @foolip would you be able to provide any information?

Does the Fullscreen API exit full screen if the document is navigated to another origin?
Does the Fullscreen API exits out of full screen if there is a fragment navigation. And if not, how it that prevented in either HTML or the FullScreen spec?

**Comment by marcoscaceres** [comment]
(Conversely, how does the Fullscreen API hook into HTML’s navigatation algorithm to “fully exit fullscreen”; and how does Fullscreen prevent “fully exit fullscreen” on fragment navigation? - we were unable to aswer these questions by reading both HTML and the Fullscreen specs. Any guidance would be greatly appreciated.)

**Comment by marcoscaceres** [comment]
We have a test for this https://github.com/web-platform-tests/wpt/pull/15705/ at least.

**Comment by foolip** [comment]
@Johanna-hub 

> Does the Fullscreen API exit full screen if the document is navigated to another origin?

Yes, the hook for this is "unloading document cleanup steps" in https://fullscreen.spec.whatwg.org/#fully-exit-fullscreen. So it will also happen for same-origin navigation.

> Does the Fullscreen API exits out of full screen if there is a fragment navigation. And if not, how it that prevented in either HTML or the FullScreen spec?

I haven't followed all the steps, but I assume that "unloading document cleanup steps" isn't run in this case.

Would using that same hook work for you?

**Comment by annevk** [comment]
If Screen Orientation is restricted to Fullscreen and properly integrated, then navigation logic for Fullscreen will take care of Screen Orientation automatically.
