### ISSUE TITLE
Timing of triggering change event doesn't look right

### ISSUE THREAD

**Issue by upsuper** [w3c/screen-orientation#89]
The current spec says:

> Whenever **the viewport is drawn at a different angle compared to the device's natural orientation**, the user agent MUST ... Queue a task to fire a simple event named change at doc 's screen.orientation object.

There are several issues here:
1. When is the viewport drawn? Shouldn't it be drawn every animation frame? Should `change` event be fired for each animation frame? (I suppose apparently it shouldn't.)
2. There is no definition of what "device's natural orientation" is.
3. Why should the event be fired when the orientation is different from a given orientation? Shouldn't it be fired whenever the document's current orientation type or angle is changed?

**Comment by mounirlamouri** [comment]
I believe bc42f9c addresses your comment. WDYT?
