### ISSUE TITLE
Allow lock Orientation more than one orientation

### ISSUE THREAD

**Issue by jvjvjv** [w3c/screen-orientation#91]
I'd like to see screen orientation allow more than one. for example, I'd like to to be able to do the following:

```
 screen.lockOrientation(['portrait-primary','landscape']);
```

**Comment by mounirlamouri** [comment]
This used to be in the spec but has been removed because it wasn't implementable on Android and we have no browser implementations outside of Android no that meant that we would specify something that no one would have implemented.

We should reconsider this when we get implementation feedback.

**Comment by purplecabbage** [comment]
+1 to include this functionality
I believe it IS implementable in cordova-android.
Just as an fyi, we have already begun implementing the spec in [cordova-plugin-screen-orientation](https://github.com/apache/cordova-plugin-screen-orientation)

**Comment by mounirlamouri** [comment]
What would be your use cases for this?

**Comment by purplecabbage** [comment]
@jvjvjv might be able to provide more, but if you have an app where you either want the front facing camera on the left or the top, you could choose [portrait-primary, landscape-primary] although I guess this could just be achieved with 'natural' ... but there absolutely could be some 'unnatural' requirements as well.

**Comment by jvjvjv** [comment]
@purplecabbage is on a track that I was on when I was thinking about it. I'm actually in the middle of developing something where I need to offer portrait-primary because the app was just in that position, but also allow the device to be turned into landscape mode so the user can perform the actual task. Upside-down is not even supported in this application, which means unlocking orientation is not the correct answer.
