### ISSUE TITLE
screen-orientation.change events should be cancellable

### ISSUE THREAD

**Issue by purplecabbage** [w3c/screen-orientation#92]
userland code should be given the chance to ignore the event and prevent the orientation from changing.

```
function onOrientationChange(evt) {
    if(evt.target.type !== 'landscape-primary') {
        evt.preventDefault();
    }
}
```

**Comment by marcoscaceres** [comment]
These report after the orientation has already changed, not before... so default can't be prevented. 

To prevent the default, one uses the API to lock the orientation to what your app needs.
