### ISSUE TITLE
Event firing needs fixes

### ISSUE THREAD

**Issue by domenic** [w3c/screen-orientation#93]
"Fire a simple event" has been removed. Instead just use [fire an event](https://dom.spec.whatwg.org/#concept-event-fire).

Also, very importantly, since you are firing the events from asynchronous browser code, you need to specify which constructor you are using. So e.g.

> "[Fire an event] named `change` at _doc_'s `screen.orientation` object, using the `Event` constructor from _doc_'s [relevant Realm]"

/cc @annevk @bzbarsky

**Comment by annevk** [comment]
With "fire an event" you don't have to define the Realm since we just grab it from the target. That's the nice thing about using "fire an event".

**Comment by domenic** [comment]
Oh yeah, I forgot we merged that. Well, I guess that's just another reason why it's important to reference the up to date "fire an event"

**Comment by marcoscaceres** [comment]
fancy!
