### ISSUE TITLE
Lacks a privacy and security consideration section

### ISSUE THREAD

**Issue by wseltzer** [w3c/screen-orientation#96]
Please include information from the security and privacy self-review, even if it's an explanation why you see no privacy issues.

**Comment by tomrittervg** [comment]
As mentioned in https://www.w3.org/2001/tag/doc/unsanctioned-tracking/ :

> [the TAG b]elieves that, because combatting fingerprinting is difficult, new Web specifications should take reasonable measures to avoid adding unneeded fingerprinting surface area. However, added surface area should not be a primary factor in determining whether to add a new feature.
[the TAG a]sserts that when a new feature does add fingerprinting surface area, it should be documented as such.

**Comment by xfq** [comment]
Fixed in #115 and #121.
