### ISSUE TITLE
Clarify in which animation frame task events are fired

### ISSUE THREAD

**Issue by foolip** [w3c/screen-orientation#97]
https://w3c.github.io/screen-orientation/#handling-screen-orientation-changes

Although animation frame tasks aren't actually defined properly yet, they will have to be a per-browsing context concept, similar to `window.requestAnimationFrame()`.

For screen orientation, it hopefully works to change the structure to "for each animation frame task enqueue an animation frame task to ...". In the absence of a spec, the discussion in https://github.com/whatwg/html/issues/707#issuecomment-265721620 might be helpful.

**Comment by xfq** [comment]
Given that https://github.com/whatwg/html/pull/2627 has been closed, mark this issue as "future" for now.

**Comment by annevk** [comment]
Let's fold this into #136.
