### ISSUE TITLE
Orientation angle cannot be precisely mapped to orientation type for devices with 1:1 screen size ratio

### ISSUE THREAD

**Issue by alexshalamov** [w3c/screen-orientation#99]
According to steps in chapter 4.1 (Step 2), devices that have screen with 1:1 aspect ratio, will always have portrait-primary or portrait-secondary orientation type. This will lead to the cases, when same orientation types are mapped to different angle values.

**Comment by pozdnyakov** [comment]
I guess same applies for round displays

**Comment by xfq** [comment]
Any suggestion on how to solve this issue? Introduce a new orientation type such as `square`?

**Comment by mounirlamouri** [comment]
At the moment, I would suggest to keep this UA specific. Chrome would most likely do what's mentioned above and each orientation would have a different angle. What would `square` do?

**Comment by xfq** [comment]
> At the moment, I would suggest to keep this UA specific. Chrome would most likely do what's mentioned above and each orientation would have a different angle.

Looks good to me.

> What would `square` do?

Initially I thought it would be the value returned by `screen.orientation.type` when the screen width is equal to the screen height, but now I find it will not solve this issue at all...

**Comment by xfq** [comment]
So can this issue be closed now?

**Comment by alexshalamov** [comment]
@xfq If specification would leave decision for mapping between screen ratio and orientation type (requires algorithm change) to the UA, then this issue can be closed.

At the moment, normative [section of the spec](https://w3c.github.io/screen-orientation/#reading-the-screen-orientation) defines how orientation type is inferred from the rendering surface ratio, and the algorithm is not sufficient for 1:1 aspect ratio.

**Comment by xfq** [comment]
@alexshalamov IIUC you're referring to the following sentence:

> if the screen width is less than or equal to the screen height, set the document's current orientation type to `portrait-primary` or `portrait-secondary`.

Do you mean we should to extract the "or equal to the screen height" part to a new step, and say the current orientation type can be `landscape-primary`, `landscape-secondary`, `portrait-primary`, or `portrait-secondary`, depending on the user agent?

**Comment by alexshalamov** [comment]
@xfq In cases when width == height, orientation type would be always portrait-primary or portrait-secondary, therefore, according to:

> However, a user agent MUST keep the current orientation type and the current orientation angle relation consistent for any given document.

When user starts rotating device and orientation of the rendering surface changes, there would be cases when actual angle of the document would be not in sync with angle that is mapped to the orientation type.

**Comment by mounirlamouri** [comment]
Practically, are there devices that have rotating angles?

**Comment by alexshalamov** [comment]
@mounirlamouri Sorry, I didn't understand the question. Most of the platforms provide data about rotation of a display (rendering area) in relation to natural (physical) orientation.

**Comment by mounirlamouri** [comment]
What I meant is whether there are devices where the actual rotation angle can be say 15 degrees?

**Comment by alexshalamov** [comment]
I'm not aware of platforms where WM would provide angles that are not multiples of 90°

**Comment by marcoscaceres** [comment]
Closing for now.
